services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-meeting-migrate
    entrypoint:
      [
        "migrate",
        "-path",
        "migration",
        "-database",
        "postgres://ighfarhasbiash@db:5432/meeting_rooms_fp?sslmode=disable",
        "up",
      ]
    depends_on:
      - db
    networks:
      - app-network
    restart: "no" # hanya jalan sekali

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-meeting-api
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    ports:
      - "8082:8080"
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=ighfarhasbiash
      - POSTGRES_DB=meeting_rooms_fp
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:alpine3.22
    container_name: redis_db
    ports:
      - "6378:6379"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  app-network:
    name: app-network
